[package]
name = "the-blockheads-tools-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
flate2 = { workspace = true }
lmdb-rs = { workspace = true }
maybe-owned = "0.3.4"
plist = { workspace = true }
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
