[package]
name = "the-blockheads-tools-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.31.1"
egui-macroquad = "0.17.3"
glam = "0.27"
macroquad = "0.4.14"
the-blockheads-tools-lib = { workspace = true }

