[package]
name = "the-blockheads-tools-gui"
version = "0.1.0"
edition = "2024"

[features]
default = []
web = ["dep:wasm-bindgen-futures"]

[dependencies]
eframe = { workspace = true, features = ["wayland", "x11"] }
wgpu = { workspace = true, features = ["dx12", "metal", "vulkan", "gles", "wgsl"] }
bytemuck = { version = "1.12", features = ["derive"] }
glam = { version = "0.30.4", features = ["bytemuck"] }
the-blockheads-tools-lib = { workspace = true }
env_logger = "0.11.8"
log = "0.4.27"
zune-png = "0.4.10"
rfd = "0.15.3"
rayon = "1.11.0"
wasm-bindgen-futures = { workspace = true, optional = true }
