[package]
name = "the-blockheads-tools-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.33.3", features = ["wgpu"] }
bytemuck = { version = "1.12", features = ["derive"] }
glam = { version = "0.30.4", features = ["bytemuck"] }
the-blockheads-tools-lib = { workspace = true }
mimalloc = "0.1.47"
env_logger = "0.11.8"
log = "0.4.27"
zune-png = "0.4.10"
rfd = "0.15.3"
rayon = "1.11.0"

