[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.85"
authors = ["med1844"]
license = "MIT"

[workspace.dependencies]
plist = "1.7.2"
flate2 = "1.1.2"
eframe = { version = "0.33.3", default-features = false, features = ["wgpu", "default_fonts"] }
wgpu = { version = "27.0.1", default-features = false, features = ["std", "parking_lot", "web", "webgpu", "webgl", "fragile-send-sync-non-atomic-wasm"] }
wasm-bindgen-futures = "0.4.58"
num_enum = "0.7.5"
snafu = "0.9.0"

the-blockheads-tools-lib = { path = "crates/lib" }
the-blockheads-tools-gui = { path = "crates/gui" }
lmdb-rs = { path = "crates/lmdb_rs" }
wgsl_macro = { path = "crates/wgsl_macro" }

[profile.wasm-release]
inherits = "release"
opt-level = 's'
lto = true
codegen-units = 1
