[project]
name = "theblockheadstools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lmdb>=1.6.2",
    "option>=2.1.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
