[package]
name = "py-bindings"
version = "0.1.0"
edition = "2021"

[lib]
name = "the_blockheads_tools_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.26.0", features = ["extension-module"] }
the-blockheads-tools-lib = { workspace = true }
num_enum = { workspace = true }
snafu = { workspace = true }
