from enum import Enum
from typing import Self, Optional


class ChunkCoord:
    """0 <= x < 2^32 - 1, 0 <= y < 32"""

    def __new__(cls, x: int, y: int) -> Self: ...
    def __init__(self, x: int, y: int) -> None: ...
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...


class ChunkBlockCoord:
    """0 <= x < 32, 0 <= y < 32"""

    def __new__(cls, x: int, y: int) -> Self: ...
    def __init__(self, x: int, y: int) -> None: ...
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...


class BlockCoord:
    """0 <= x < 2^32 - 1, 0 <= y < 1024"""

    def __new__(cls, x: int, y: int) -> Self: ...
    def __init__(self, x: int, y: int) -> None: ...
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...


class BlockType(Enum):
    Stone = 1
    Air = 2
    Water = 3
    Ice = 4
    Snow = 5
    Dirt = 6
    DesertSand = 7
    BeachSand = 8
    Wood = 9
    MinedStone = 10
    RedBrick = 11
    Limestone = 12
    MinedLimestone = 13
    Marble = 14
    MinedMarble = 15
    TimeCrystal = 16
    SandStone = 17
    MinedSandStone = 18
    RedMarble = 19
    MinedRedMarble = 20
    Glass = 24
    SpawnPortalBase = 25
    GoldBlock = 26
    GrassDirt = 27
    SnowDirt = 28
    LapisLazuli = 29
    MinedLapisLazuli = 30
    Lava = 31
    ReinforcedPlatform = 32
    SpawnPortalBaseAmethyst = 33
    SpawnPortalBaseSapphire = 34
    SpawnPortalBaseEmerald = 35
    SpawnPortalBaseRuby = 36
    SpawnPortalBaseDiamond = 37
    NorthPole = 38
    SouthPole = 39
    WestPole = 40
    EastPole = 41
    PortalBase = 42
    PortalBaseAmethyst = 43
    PortalBaseSapphire = 44
    PortalBaseEmerald = 45
    PortalBaseRuby = 46
    PortalBaseDiamond = 47
    Compost = 48
    GrassCompost = 49
    SnowCompost = 50
    Basalt = 51
    MinedBasalt = 52
    CopperBlock = 53
    TinBlock = 54
    BronzeBlock = 55
    IronBlock = 56
    SteelBlock = 57
    BlackSand = 58
    BlackGlass = 59
    TradePortalBase = 60
    TradePortalBaseAmethyst = 61
    TradePortalBaseSapphire = 62
    TradePortalBaseEmerald = 63
    TradePortalBaseRuby = 64
    TradePortalBaseDiamond = 65
    PlatinumBlock = 67
    TitaniumBlock = 68
    CarbonFiberBlock = 69
    Gravel = 70
    AmethystBlock = 71
    SapphireBlock = 72
    EmeraldBlock = 73
    RubyBlock = 74
    DiamondBlock = 75
    Plaster = 76
    LuminousPlaster = 77

    def __int__(self) -> int: ...


class Block:
    def fg(self) -> BlockType: ...


class Chunk:
    def as_bytes(self) -> bytes: ...
    def block_at(self, coord: ChunkBlockCoord) -> Block: ...


class Chunks:
    def __contains__(self, coord: ChunkCoord) -> bool: ...

    def keys(self) -> set[ChunkCoord]:
        """We create a set each time this function is called. Kinda expensive."""
        ...

    def chunk_at(self, coord: BlockCoord | ChunkCoord) -> Optional[Chunk]: ...
    def block_at(self, coord: BlockCoord) -> Optional[Block]: ...


class WorldV2:
    @property
    def blockheads_datas_v2(self) -> str: ...

    @property
    def circum_navigate_booleans_data(self) -> bytes: ...
    @circum_navigate_booleans_data.setter
    def circum_navigate_booleans_data(self, value: bytes): ...

    @property
    def creation_date(self) -> str: ...
    @property
    def distance_ordered_food_types(self) -> bytes: ...
    @distance_ordered_food_types.setter
    def distance_ordered_food_types(self, value: bytes): ...

    @property
    def expert_mode(self) -> bool: ...
    @expert_mode.setter
    def expert_mode(self, value: bool): ...

    @property
    def found_items(self) -> bytes: ...
    @found_items.setter
    def found_items(self, value: bytes): ...

    @property
    def host_port(self) -> str: ...
    @host_port.setter
    def host_port(self, value: str): ...

    @property
    def max_players(self) -> str: ...
    @max_players.setter
    def max_players(self, value: str): ...

    @property
    def migration_complete_v1_7(self) -> bool: ...
    @migration_complete_v1_7.setter
    def migration_complete_v1_7(self, value: bool): ...

    @property
    def no_rain_timer(self) -> float: ...
    @no_rain_timer.setter
    def no_rain_timer(self, value: float): ...

    @property
    def portal_level(self) -> int: ...
    @portal_level.setter
    def portal_level(self, value: int): ...

    @property
    def random_seed(self) -> int: ...
    @random_seed.setter
    def random_seed(self, value: int): ...

    @property
    def remote_game(self) -> bool: ...
    @remote_game.setter
    def remote_game(self, value: bool): ...

    @property
    def run_at_launch(self) -> bool: ...
    @run_at_launch.setter
    def run_at_launch(self, value: bool): ...

    @property
    def save_date(self) -> str: ...

    @property
    def save_id(self) -> str: ...
    @save_id.setter
    def save_id(self, value: str): ...

    @property
    def save_version(self) -> int: ...
    @save_version.setter
    def save_version(self, value: int): ...

    @property
    def start_portal_pos_x(self) -> int: ...
    @start_portal_pos_x.setter
    def start_portal_pos_x(self, value: int): ...

    @property
    def start_portal_pos_y(self) -> int: ...
    @start_portal_pos_y.setter
    def start_portal_pos_y(self, value: int): ...

    @property
    def translation(self) -> tuple[float, float]: ...
    @translation.setter
    def translation(self, value: tuple[float, float]): ...

    @property
    def world_name(self) -> str: ...
    @world_name.setter
    def world_name(self, value: str): ...

    @property
    def world_time(self) -> float: ...
    @world_time.setter
    def world_time(self, value: float): ...

    @property
    def world_width_macro(self) -> int: ...
    @world_width_macro.setter
    def world_width_macro(self, value: int): ...


class DynamicWorldV2:
    @property
    def active_blockhead_index(self) -> int: ...
    @active_blockhead_index.setter
    def active_blockhead_index(self, value: int): ...

    @property
    def dynamic_object_id_count(self) -> int: ...
    @dynamic_object_id_count.setter
    def dynamic_object_id_count(self, value: int): ...

    @property
    def save_version(self) -> int: ...
    @save_version.setter
    def save_version(self, value: int): ...

    @property
    def saved_glow_indices(self) -> bytes: ...
    @saved_glow_indices.setter
    def saved_glow_indices(self, value: bytes): ...

    @property
    def workbench_has_been_crafted(self) -> bool: ...
    @workbench_has_been_crafted.setter
    def workbench_has_been_crafted(self, value: bool): ...

    def __repr__(self) -> str: ...


class Blockhead:
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str): ...

    @property
    def clothing_increment_timer(self) -> int: ...
    @clothing_increment_timer.setter
    def clothing_increment_timer(self, value: int): ...

    @property
    def double_time_unlocked(self) -> bool: ...
    @double_time_unlocked.setter
    def double_time_unlocked(self, value: bool): ...

    @property
    def skin_options(self) -> bytes: ...
    @skin_options.setter
    def skin_options(self, value: bytes): ...

    @property
    def state(self) -> bytes: ...
    @state.setter
    def state(self, value: bytes): ...

    def __repr__(self) -> str: ...


class WorldDbMain:
    @property
    def blockheads(self) -> list[Blockhead]: ...
    @property
    def dynamic_world_v2(self) -> DynamicWorldV2: ...
    @property
    def world_v2(self) -> WorldV2: ...


class WorldDb:
    @classmethod
    def open(cls, path: str) -> Self: ...
    def save(self, path: str): ...

    @property
    def chunks(self) -> Chunks: ...

    @property
    def main(self) -> WorldDbMain: ...
