site_name: TheBlockheadsTools Docs
theme:
  name: material
site_url: https://med1844.github.io/TheBlockheadsTools/docs/
site_dir: site/docs
docs_dir: src
nav:
  - Introduction: index.md
  - Getting started:
    - Examples: getting-started/examples.md
  - Guides:
    - Setup Emulator: guides/setup-emulator.md
