# forked from https://github.com/DavidAntliff/egui-eframe-demo/blob/main/.github/workflows/pages.yml
name: Deploy Editor and Docs

on:
  push:
    branches:
      - rust

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # repo checkout
      - name: Setup toolchain for wasm
        run: |
          rustup update stable
          rustup default stable
          rustup set profile minimal
          rustup target add wasm32-unknown-unknown
      - name: Rust Cache # cache the rust build artefacts
        uses: Swatinem/rust-cache@v2
      - name: Download and install Trunk binary
        uses: jetli/trunk-action@v0.5.1
        with:
          # Optional version of trunk to install(eg. 'v0.21.14', 'latest')
          version: 'latest'
      - name: Build Editor with Trunk
        # Environment $public_url resolves to the github project page.
        # If using a user/organization page, remove the `${{ github.event.repository.name }}` part.
        # using --public-url something will allow trunk to modify all the href paths like from favicon.ico to repo_name/favicon.ico .
        # this is necessary for github pages where the site is deployed to username.github.io/repo_name and all files must be requested
        # relatively as eframe_template/favicon.ico. if we skip public-url option, the href paths will instead request username.github.io/favicon.ico which
        # will obviously return error 404 not found.
        working-directory: crates/web_gui
        run: trunk build --release --public-url $public_url
        env:
          public_url: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/editor/"
      # setup uv for mkdocs
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Set up Python
        run: uv python install
      - name: Build MkDocs
        working-directory: docs
        run: uv run mkdocs build --strict
      - name: Prepare deployment folder
        run: |
          mkdir staging
          mkdir -p staging/editor
          cp -r crates/web_gui/dist/* staging/editor/
          cp -r docs/site/docs staging/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: staging

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
