name: Prek checks
on: [push, pull_request]

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Set up Python
        run: uv python install
      - name: Setup wasm32
        run: rustup target add wasm32-unknown-unknown
      - uses: j178/prek-action@v1
